version: '3'
services:
  my-app: 
    image: 201388815052.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
    ports: 
     - 3000:3000
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME="${ROOT_USERNAME}"
     - MONGO_INITDB_ROOT_PASSWORD="${ROOT_PASSWORD}"
    volumes:
     - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
     - 8080:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME="${MONGODB_ADMINUSERNAME}"
     - ME_CONFIG_MONGODB_ADMINPASSWORD="${MONGODB_ADMINPASSWORD}"
     - ME_CONFIG_MONGODB_SERVER="${MONGODB_SERVER}"
    depends_on:
     - "mongodb"
volumes:
  mongo-data:
    driver: local

     

